/**
 * Trusted Product & Service Catalog
 * Prices in TND (Tunisian Dinar).
 * The server/engine validates all quote totals against this catalog.
 */
import { CatalogProduct } from '../types';

export const CATALOG_PRODUCTS: CatalogProduct[] = [
  // CAMERAS
  {
    id: 'prod_cam_4mp_turret',
    sku: 'HIK-DS2CD2347G2',
    name: 'Hikvision ColorVu 4MP PoE Turret IP Camera',
    category: 'CAMERAS',
    unitPrice: 285.00,
    unit: 'pcs',
    description: '4 Megapixel 24/7 full-color imaging, F1.0 aperture, built-in mic, IP67 weatherproof.',
    inStock: 48,
  },
  {
    id: 'prod_cam_4k_bullet',
    sku: 'DH-IPC-HFW2831T',
    name: 'Dahua 8MP 4K WDR IR Bullet Camera',
    category: 'CAMERAS',
    unitPrice: 360.00,
    unit: 'pcs',
    description: '4K Ultra HD motorized varifocal, 60m Smart IR, Starlight technology, metal housing.',
    inStock: 24,
  },
  {
    id: 'prod_cam_ptz_speed_dome',
    sku: 'HIK-DE4425IW-DE',
    name: 'Hikvision 4MP 25x Optical Zoom PTZ Speed Dome',
    category: 'CAMERAS',
    unitPrice: 1450.00,
    unit: 'pcs',
    description: 'Perimeter defense, auto-tracking 3.0, 100m IR distance, ultra-low light DarkFighter.',
    inStock: 6,
  },

  // RECORDERS & STORAGE
  {
    id: 'prod_nvr_8ch_poe',
    sku: 'HIK-DS7608NXI-I2-8P',
    name: 'Hikvision AcuSense 8-Channel 4K PoE NVR',
    category: 'RECORDERS',
    unitPrice: 590.00,
    unit: 'pcs',
    description: '8 independent PoE ports, 80Mbps bandwidth, human/vehicle target classification, H.265+.',
    inStock: 16,
  },
  {
    id: 'prod_nvr_16ch_poe',
    sku: 'DH-NVR5216-16P-4KS2E',
    name: 'Dahua Pro 16-Channel 4K 16-PoE NVR',
    category: 'RECORDERS',
    unitPrice: 890.00,
    unit: 'pcs',
    description: '16 PoE ports, ePoE long-range 800m, 320Mbps incoming bandwidth, 2 SATA bays.',
    inStock: 10,
  },
  {
    id: 'prod_hdd_4tb_purple',
    sku: 'WD-PURPLE-4TB',
    name: 'Western Digital Purple 4TB Surveillance HDD',
    category: 'RECORDERS',
    unitPrice: 320.00,
    unit: 'pcs',
    description: 'AllFrame AI technology, engineered for 24/7 continuous high-definition recording, 3-year warranty.',
    inStock: 35,
  },
  {
    id: 'prod_hdd_8tb_purple',
    sku: 'WD-PURPLE-8TB',
    name: 'Western Digital Purple Pro 8TB Enterprise HDD',
    category: 'RECORDERS',
    unitPrice: 620.00,
    unit: 'pcs',
    description: 'Enterprise-class workload rate up to 550 TB/yr, 2.5 million hours MTBF.',
    inStock: 14,
  },

  // NETWORKING & WI-FI
  {
    id: 'prod_switch_poe_8port',
    sku: 'UTP-7208E-POE',
    name: 'Managed Gigabit 8-Port PoE+ Switch (120W)',
    category: 'NETWORKING',
    unitPrice: 240.00,
    unit: 'pcs',
    description: '8 x Gigabit PoE+ ports (802.3at/af), 2 x Gigabit SFP uplinks, surge protection 6kV.',
    inStock: 28,
  },
  {
    id: 'prod_switch_poe_16port',
    sku: 'UTP-7216E-POE',
    name: 'Gigabit 16-Port PoE+ Rackmount Switch (250W)',
    category: 'NETWORKING',
    unitPrice: 520.00,
    unit: 'pcs',
    description: '16 x Gigabit PoE ports, 2 x combo SFP, CCTV mode 250m transmission, QoS priority.',
    inStock: 12,
  },
  {
    id: 'prod_ap_wifi6_unifi',
    sku: 'U6-PRO',
    name: 'Ubiquiti UniFi 6 Pro Access Point (Wi-Fi 6)',
    category: 'NETWORKING',
    unitPrice: 480.00,
    unit: 'pcs',
    description: 'Dual-band Wi-Fi 6, 5.3 Gbps aggregate throughput, 300+ client capacity, ceiling mount.',
    inStock: 20,
  },
  {
    id: 'prod_router_cloud_gateway',
    sku: 'UXG-MAX',
    name: 'UniFi Next-Gen Multi-Gigabit Cloud Gateway',
    category: 'NETWORKING',
    unitPrice: 680.00,
    unit: 'pcs',
    description: '1.5 Gbps routing with IDS/IPS, dual WAN failover, integrated firewall and VPN server.',
    inStock: 8,
  },

  // CABLING & ACCESSORIES
  {
    id: 'prod_cable_cat6_roll',
    sku: 'CAB-CAT6-UTP-305',
    name: 'Cat6 UTP 100% Solid Copper Drum (305m)',
    category: 'CABLES',
    unitPrice: 260.00,
    unit: 'roll',
    description: 'Pure bare copper 23AWG, 250MHz bandwidth, LSZH flame-retardant outer jacket.',
    inStock: 42,
  },
  {
    id: 'prod_rack_9u_cabinet',
    sku: 'RCK-WALL-9U-600',
    name: '19-Inch 9U Wall Mount Server Rack Enclosure',
    category: 'ACCESSORIES',
    unitPrice: 290.00,
    unit: 'pcs',
    description: 'Toughened glass door, removable side panels, cooling fan unit, cable entry glands.',
    inStock: 15,
  },
  {
    id: 'prod_ups_backup_1200va',
    sku: 'UPS-ONLINE-1200',
    name: 'Line-Interactive UPS 1200VA / 720W with AVR',
    category: 'ACCESSORIES',
    unitPrice: 310.00,
    unit: 'pcs',
    description: 'Battery backup for NVR & PoE switch during grid outages, surge protection.',
    inStock: 18,
  },

  // ACCESS CONTROL
  {
    id: 'prod_access_facial_terminal',
    sku: 'HIK-K1T671MF',
    name: 'Biometric Face Recognition & RFID Access Terminal',
    category: 'ACCESS',
    unitPrice: 940.00,
    unit: 'pcs',
    description: '7-inch LCD touch screen, 50,000 faces capacity, live face spoof prevention, Mifare RFID.',
    inStock: 9,
  },
  {
    id: 'prod_maglock_280kg',
    sku: 'MAG-LOCK-600LBS',
    name: 'Electromagnetic Door Lock 280kg (600lbs) with LED',
    category: 'ACCESS',
    unitPrice: 165.00,
    unit: 'pcs',
    description: 'Fail-safe magnetic lock with bond sensor status output, aluminum alloy, 12VDC.',
    inStock: 30,
  },

  // LABOUR & ENGINEERING SERVICES
  {
    id: 'serv_survey_engineering',
    sku: 'SRV-SURVEY-ENG',
    name: 'On-site Technical Survey, Cable Pathway & Risk Assessment',
    category: 'SERVICES',
    unitPrice: 120.00,
    unit: 'service',
    description: 'Pre-installation survey by certified senior systems engineer with photographic documentation.',
    inStock: 999,
  },
  {
    id: 'serv_cctv_install_per_cam',
    sku: 'SRV-CAM-INSTALL',
    name: 'Camera Mounting, Conduit & Cable Pulling (per camera)',
    category: 'SERVICES',
    unitPrice: 85.00,
    unit: 'unit',
    description: 'Physical installation, weatherproofing, conduit installation, RJ45 termination and alignment.',
    inStock: 999,
  },
  {
    id: 'serv_nvr_config_remote',
    sku: 'SRV-NVR-CONFIG',
    name: 'NVR System Commissioning, Storage Allocation & P2P Cloud Setup',
    category: 'SERVICES',
    unitPrice: 180.00,
    unit: 'service',
    description: 'Firmware hardening, motion detection zones, recording schedule, smartphone app setup and staff handover.',
    inStock: 999,
  },
  {
    id: 'serv_wifi_deployment_per_ap',
    sku: 'SRV-WIFI-DEPLOY',
    name: 'Wi-Fi AP Installation, Cabling & Roaming Optimization',
    category: 'SERVICES',
    unitPrice: 95.00,
    unit: 'unit',
    description: 'Ceiling mount, drop cable, RF channel allocation, power output balancing, and speed verification.',
    inStock: 999,
  },
  {
    id: 'serv_access_control_door',
    sku: 'SRV-DOOR-INSTALL',
    name: 'Door Access Control Installation & Controller Wiring (per door)',
    category: 'SERVICES',
    unitPrice: 220.00,
    unit: 'door',
    description: 'Lock mounting, break-glass unit, exit button, power supply wiring, and safety testing.',
    inStock: 999,
  },
];
