/**
 * Initial Mock Database Seed
 * Mirrors Firebase Firestore collections for SecurOps.
 */
import { 
  UserProfile, 
  ServiceRequest, 
  WorkOrder, 
  WorkflowTask, 
  Quote, 
  Invoice, 
  InstalledEquipment, 
  ServiceReport, 
  Appointment, 
  AuditEntry 
} from '../types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user_super_admin',
    name: 'Karim Mansour',
    email: 'k.mansour@securops.tn',
    role: 'SUPER_ADMIN',
    phone: '+216 98 100 200',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_admin',
    name: 'Sonia Guesmi',
    email: 's.guesmi@securops.tn',
    role: 'ADMIN',
    phone: '+216 97 220 330',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_tech_slimane',
    name: 'Slimane Trabelsi',
    email: 's.trabelsi@securops.tn',
    role: 'TECHNICIAN',
    phone: '+216 96 330 440',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    activeJobsCount: 3,
  },
  {
    id: 'user_tech_zied',
    name: 'Zied Khelil',
    email: 'z.khelil@securops.tn',
    role: 'TECHNICIAN',
    phone: '+216 95 440 550',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    activeJobsCount: 2,
  },
  {
    id: 'user_accountant',
    name: 'Mona Chaabane',
    email: 'm.chaabane@securops.tn',
    role: 'ACCOUNTANT',
    phone: '+216 94 550 660',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_REQUESTS: ServiceRequest[] = [
  {
    id: 'REQ-001024',
    customerName: 'Ahmed Ben Ali',
    customerPhone: '+216 98 421 890',
    customerEmail: 'ahmed.benali@gmail.com',
    serviceType: 'cctv_installation',
    serviceName: 'CCTV Security Camera Installation',
    location: 'Gabès',
    address: 'Avenue Habib Bourguiba, Gabès 6000',
    description: 'Need 4 high-definition IP cameras for retail store front, cash desk, and warehouse backroom. Remote smartphone viewing required.',
    photos: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80',
    ],
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(), // 3 hours ago
    status: 'NEW',
    urgency: 'HIGH',
  },
  {
    id: 'REQ-001025',
    customerName: 'Société El Manar S.A.',
    customerPhone: '+216 71 854 220',
    customerEmail: 'it@elmanar-group.com',
    serviceType: 'wifi_installation',
    serviceName: 'Enterprise Wi-Fi & Mesh Network',
    location: 'Tunis',
    address: 'Zone Urbaine Nord, Imm. Horizon, Tunis 1082',
    description: 'Two-story engineering office (~450m²), 50 employees complaining about weak Wi-Fi dead zones. Need 4 to 6 ceiling APs with guest isolation.',
    photos: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=600&auto=format&fit=crop&q=80',
    ],
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(), // 8 hours ago
    status: 'NEW',
    urgency: 'NORMAL',
  },
  {
    id: 'REQ-001026',
    customerName: 'Clinique Médicale Ibn Sina',
    customerPhone: '+216 73 228 114',
    customerEmail: 'direction@clinique-ibnsina.tn',
    serviceType: 'access_control_installation',
    serviceName: 'Biometric Access Control & Intercom',
    location: 'Sousse',
    address: 'Boulevard 14 Janvier, Sousse 4000',
    description: 'Require biometric facial recognition and magnetic locks for operating theater doors and drug storage vault.',
    photos: [
      'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600&auto=format&fit=crop&q=80',
    ],
    createdAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    status: 'NEW',
    urgency: 'URGENT',
  },
  {
    id: 'REQ-001027',
    customerName: 'Résidence Les Jasmins',
    customerPhone: '+216 93 112 334',
    customerEmail: 'syndic.lesjasmins@gmail.com',
    serviceType: 'alarm_installation',
    serviceName: 'Intruder Alarm & Perimeter Defense',
    location: 'Ariana',
    address: 'Ennasr 2, Ariana 2037',
    description: 'Syndic building perimeter defense. 6 external PIR sensors, solar strobe siren, GSM SIM alerting unit.',
    photos: [],
    createdAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    status: 'NEW',
    urgency: 'NORMAL',
  },
  {
    id: 'REQ-001028',
    customerName: 'Hotel Oasis Djerba',
    customerPhone: '+216 75 750 880',
    customerEmail: 'tech@oasis-djerba.com',
    serviceType: 'iptv_installation',
    serviceName: 'Commercial IPTV & Hospitality Streaming',
    location: 'Djerba',
    address: 'Zone Touristique Midoun, Djerba 4116',
    description: '80 room smart TV IPTV distribution with French, Italian, and German satellite bouquets.',
    photos: [],
    createdAt: new Date(Date.now() - 3600000 * 42).toISOString(),
    status: 'NEW',
    urgency: 'NORMAL',
  },
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'WO-001022',
    serviceRequestId: 'REQ-001020',
    customerId: 'cust_abc_logistics',
    customerName: 'ABC Logistics Hub',
    customerPhone: '+216 74 445 600',
    customerEmail: 'operations@abclogistics.tn',
    siteCity: 'Sfax',
    siteAddress: 'Port de Commerce, Hangar 4B, Sfax 3000',
    serviceType: 'cctv_installation',
    serviceName: 'CCTV Security Camera Installation',
    status: 'WORK_AUTHORIZED',
    progressPercentage: 55,
    assignedTechnicianIds: ['user_tech_slimane'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    authorizedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    currentStepId: 'prepare_equipment',
    quoteId: 'QUO-001022',
    invoiceId: 'INV-001022',
    taskIds: [
      'TSK-1022-01',
      'TSK-1022-02',
      'TSK-1022-03',
      'TSK-1022-04',
      'TSK-1022-05',
      'TSK-1022-06',
      'TSK-1022-07',
      'TSK-1022-08',
      'TSK-1022-09',
      'TSK-1022-10',
      'TSK-1022-11',
    ],
    overrideHistory: [],
  },
  {
    id: 'WO-001023',
    serviceRequestId: 'REQ-001021',
    customerId: 'cust_cafe_carthage',
    customerName: 'Café & Lounge Carthage',
    customerPhone: '+216 98 333 444',
    customerEmail: 'contact@cafecarthage.tn',
    siteCity: 'La Marsa',
    siteAddress: 'Corniche de La Marsa, Tunis 2070',
    serviceType: 'wifi_installation',
    serviceName: 'Enterprise Wi-Fi & Mesh Network',
    status: 'WAITING_PAYMENT',
    progressPercentage: 45,
    assignedTechnicianIds: ['user_tech_zied'],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    currentStepId: 'payment_confirmation',
    quoteId: 'QUO-001023',
    invoiceId: 'INV-001023',
    taskIds: [
      'TSK-1023-01',
      'TSK-1023-02',
      'TSK-1023-03',
      'TSK-1023-04',
      'TSK-1023-05',
      'TSK-1023-06',
      'TSK-1023-07',
      'TSK-1023-08',
      'TSK-1023-09',
      'TSK-1023-10',
      'TSK-1023-11',
    ],
    overrideHistory: [],
  },
];

export const INITIAL_TASKS: WorkflowTask[] = [
  // Tasks for WO-001022 (ABC Logistics Hub - Paid & Authorized!)
  {
    id: 'TSK-1022-01',
    workOrderId: 'WO-001022',
    templateStepId: 'contact_customer',
    title: 'Contact Customer & Verify Needs',
    type: 'CONTACT',
    status: 'COMPLETED',
    order: 1,
    assignedTo: 'user_admin',
    assignedRole: 'ADMIN',
    completedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    dependencies: [],
    notes: 'Contacted logistics manager Mr. Karim. Scheduled site survey for following morning.',
  },
  {
    id: 'TSK-1022-02',
    workOrderId: 'WO-001022',
    templateStepId: 'site_visit',
    title: 'Conduct Site Survey & Technical Inspection',
    type: 'SITE_VISIT',
    status: 'COMPLETED',
    order: 2,
    assignedTo: 'user_tech_slimane',
    assignedRole: 'TECHNICIAN',
    completedAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    dependencies: ['contact_customer'],
    notes: 'Completed warehouse survey. High ceiling (6.5m) requires motorized boom lift. Cable distance 180m.',
  },
  {
    id: 'TSK-1022-03',
    workOrderId: 'WO-001022',
    templateStepId: 'create_quote',
    title: 'Create Quotation & Bill of Quantities',
    type: 'CREATE_QUOTE',
    status: 'COMPLETED',
    order: 3,
    assignedTo: 'user_admin',
    assignedRole: 'ADMIN',
    completedAt: new Date(Date.now() - 86400000 * 1.2).toISOString(),
    dependencies: ['site_visit'],
    notes: 'Generated Quote v1 for 4x 4K Bullet Cameras + 8Ch NVR + 4TB WD Purple. Total: 3,420 TND.',
  },
  {
    id: 'TSK-1022-04',
    workOrderId: 'WO-001022',
    templateStepId: 'customer_approval',
    title: 'Customer Approval of Quote',
    type: 'CUSTOMER_APPROVAL',
    status: 'COMPLETED',
    order: 4,
    assignedTo: 'user_admin',
    assignedRole: 'ADMIN',
    completedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    dependencies: ['create_quote'],
    notes: 'Customer accepted Quote QUO-001022 formally via online portal.',
  },
  {
    id: 'TSK-1022-05',
    workOrderId: 'WO-001022',
    templateStepId: 'create_invoice',
    title: 'Generate Pro-forma / Commercial Invoice',
    type: 'CREATE_INVOICE',
    status: 'COMPLETED',
    order: 5,
    assignedTo: 'user_accountant',
    assignedRole: 'ACCOUNTANT',
    completedAt: new Date(Date.now() - 86400000 * 0.8).toISOString(),
    dependencies: ['customer_approval'],
    notes: 'Issued Invoice INV-001022 for 3,420 TND.',
  },
  {
    id: 'TSK-1022-06',
    workOrderId: 'WO-001022',
    templateStepId: 'payment_confirmation',
    title: 'Payment Confirmation & Commercial Gate',
    type: 'PAYMENT',
    status: 'COMPLETED',
    order: 6,
    assignedTo: 'user_admin',
    assignedRole: 'ADMIN',
    completedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    dependencies: ['create_invoice'],
    notes: 'Confirmed 100% bank transfer via Attijari Bank ref TRF-992019. WORK AUTHORIZED!',
  },
  {
    id: 'TSK-1022-07',
    workOrderId: 'WO-001022',
    templateStepId: 'prepare_equipment',
    title: 'Pick & Prepare Warehouse Equipment',
    type: 'PREPARE_EQUIPMENT',
    status: 'TODO',
    order: 7,
    assignedTo: 'user_tech_slimane',
    assignedRole: 'TECHNICIAN',
    dependencies: ['payment_confirmation'],
    notes: 'Ready for technician to pull 4 cameras, NVR, 200m Cat6 and patch cables from store.',
  },
  {
    id: 'TSK-1022-08',
    workOrderId: 'WO-001022',
    templateStepId: 'mount_and_cabling',
    title: 'Cable Pulling & Physical Camera Mounting',
    type: 'INSTALLATION',
    status: 'LOCKED',
    order: 8,
    assignedTo: 'user_tech_slimane',
    assignedRole: 'TECHNICIAN',
    dependencies: ['prepare_equipment'],
  },
  {
    id: 'TSK-1022-09',
    workOrderId: 'WO-001022',
    templateStepId: 'configuration',
    title: 'Configure NVR, Motion Zones & P2P App',
    type: 'CONFIGURATION',
    status: 'LOCKED',
    order: 9,
    assignedTo: 'user_tech_slimane',
    assignedRole: 'TECHNICIAN',
    dependencies: ['mount_and_cabling'],
  },
  {
    id: 'TSK-1022-10',
    workOrderId: 'WO-001022',
    templateStepId: 'system_testing',
    title: 'System Commissioning & Angle Verification',
    type: 'TESTING',
    status: 'LOCKED',
    order: 10,
    assignedTo: 'user_tech_slimane',
    assignedRole: 'TECHNICIAN',
    dependencies: ['configuration'],
  },
  {
    id: 'TSK-1022-11',
    workOrderId: 'WO-001022',
    templateStepId: 'customer_confirmation',
    title: 'Customer Training, Handover & Sign-off',
    type: 'CUSTOMER_CONFIRMATION',
    status: 'LOCKED',
    order: 11,
    assignedTo: 'user_tech_slimane',
    assignedRole: 'TECHNICIAN',
    dependencies: ['system_testing'],
  },

  // Tasks for WO-001023 (Café Carthage - Waiting for payment!)
  {
    id: 'TSK-1023-01',
    workOrderId: 'WO-001023',
    templateStepId: 'contact_customer',
    title: 'Contact Customer & Verify Needs',
    type: 'CONTACT',
    status: 'COMPLETED',
    order: 1,
    assignedTo: 'user_admin',
    assignedRole: 'ADMIN',
    completedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    dependencies: [],
  },
  {
    id: 'TSK-1023-02',
    workOrderId: 'WO-001023',
    templateStepId: 'site_visit',
    title: 'RF Site Survey & AP Placement Survey',
    type: 'SITE_VISIT',
    status: 'COMPLETED',
    order: 2,
    assignedTo: 'user_tech_zied',
    assignedRole: 'TECHNICIAN',
    completedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    dependencies: ['contact_customer'],
  },
  {
    id: 'TSK-1023-03',
    workOrderId: 'WO-001023',
    templateStepId: 'create_quote',
    title: 'Prepare Wi-Fi Proposal & Equipment BOM',
    type: 'CREATE_QUOTE',
    status: 'COMPLETED',
    order: 3,
    assignedTo: 'user_admin',
    assignedRole: 'ADMIN',
    completedAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    dependencies: ['site_visit'],
  },
  {
    id: 'TSK-1023-04',
    workOrderId: 'WO-001023',
    templateStepId: 'customer_approval',
    title: 'Customer Approval of Quote',
    type: 'CUSTOMER_APPROVAL',
    status: 'COMPLETED',
    order: 4,
    assignedTo: 'user_admin',
    assignedRole: 'ADMIN',
    completedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    dependencies: ['create_quote'],
  },
  {
    id: 'TSK-1023-05',
    workOrderId: 'WO-001023',
    templateStepId: 'create_invoice',
    title: 'Generate Pro-forma / Commercial Invoice',
    type: 'CREATE_INVOICE',
    status: 'COMPLETED',
    order: 5,
    assignedTo: 'user_accountant',
    assignedRole: 'ACCOUNTANT',
    completedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    dependencies: ['customer_approval'],
  },
  {
    id: 'TSK-1023-06',
    workOrderId: 'WO-001023',
    templateStepId: 'payment_confirmation',
    title: 'Payment Confirmation & Commercial Gate',
    type: 'PAYMENT',
    status: 'TODO',
    order: 6,
    assignedTo: 'user_admin',
    assignedRole: 'ADMIN',
    dependencies: ['create_invoice'],
    notes: 'Invoice #INV-001023 sent to client. Awaiting bank receipt or cash payment before unlocking AP deployment.',
  },
  {
    id: 'TSK-1023-07',
    workOrderId: 'WO-001023',
    templateStepId: 'prepare_equipment',
    title: 'Flash Firmware & Adopt APs in Controller',
    type: 'PREPARE_EQUIPMENT',
    status: 'LOCKED',
    order: 7,
    assignedTo: 'user_tech_zied',
    assignedRole: 'TECHNICIAN',
    dependencies: ['payment_confirmation'],
  },
  {
    id: 'TSK-1023-08',
    workOrderId: 'WO-001023',
    templateStepId: 'mount_and_cabling',
    title: 'Install Cat6 Drops & Mount Access Points',
    type: 'INSTALLATION',
    status: 'LOCKED',
    order: 8,
    assignedTo: 'user_tech_zied',
    assignedRole: 'TECHNICIAN',
    dependencies: ['prepare_equipment'],
  },
  {
    id: 'TSK-1023-09',
    workOrderId: 'WO-001023',
    templateStepId: 'configuration',
    title: 'Configure SSIDs, VLANs & Guest Portal',
    type: 'CONFIGURATION',
    status: 'LOCKED',
    order: 9,
    assignedTo: 'user_tech_zied',
    assignedRole: 'TECHNICIAN',
    dependencies: ['mount_and_cabling'],
  },
  {
    id: 'TSK-1023-10',
    workOrderId: 'WO-001023',
    templateStepId: 'system_testing',
    title: 'Throughput Speed Test & Roaming Audit',
    type: 'TESTING',
    status: 'LOCKED',
    order: 10,
    assignedTo: 'user_tech_zied',
    assignedRole: 'TECHNICIAN',
    dependencies: ['configuration'],
  },
  {
    id: 'TSK-1023-11',
    workOrderId: 'WO-001023',
    templateStepId: 'customer_confirmation',
    title: 'Deliver Credentials & Customer Sign-off',
    type: 'CUSTOMER_CONFIRMATION',
    status: 'LOCKED',
    order: 11,
    assignedTo: 'user_tech_zied',
    assignedRole: 'TECHNICIAN',
    dependencies: ['system_testing'],
  },
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: 'QUO-001022',
    workOrderId: 'WO-001022',
    customerId: 'cust_abc_logistics',
    customerName: 'ABC Logistics Hub',
    currentVersion: 1,
    status: 'ACCEPTED',
    validUntil: new Date(Date.now() + 86400000 * 30).toISOString(),
    sentAt: new Date(Date.now() - 86400000 * 1.2).toISOString(),
    acceptedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    versions: [
      {
        version: 1,
        items: [
          { id: 'qi_1', productId: 'prod_cam_4k_bullet', name: 'Dahua 8MP 4K WDR IR Bullet Camera', type: 'product', quantity: 4, unitPrice: 360, total: 1440 },
          { id: 'qi_2', productId: 'prod_nvr_8ch_poe', name: 'Hikvision AcuSense 8-Channel 4K PoE NVR', type: 'product', quantity: 1, unitPrice: 590, total: 590 },
          { id: 'qi_3', productId: 'prod_hdd_4tb_purple', name: 'Western Digital Purple 4TB Surveillance HDD', type: 'product', quantity: 1, unitPrice: 320, total: 320 },
          { id: 'qi_4', productId: 'prod_cable_cat6_roll', name: 'Cat6 UTP 100% Solid Copper Drum (305m)', type: 'product', quantity: 1, unitPrice: 260, total: 260 },
          { id: 'qi_5', productId: 'serv_cctv_install_per_cam', name: 'Camera Mounting, Conduit & Cable Pulling', type: 'service', quantity: 4, unitPrice: 85, total: 340 },
          { id: 'qi_6', productId: 'serv_nvr_config_remote', name: 'NVR System Commissioning & P2P Cloud Setup', type: 'service', quantity: 1, unitPrice: 180, total: 180 },
        ],
        subtotal: 3130.00,
        discount: 130.00,
        taxRate: 0.19,
        taxAmount: 570.00,
        total: 3570.00,
        notes: 'Commercial installation warranty: 24 months on hardware, 12 months on workmanship.',
        createdAt: new Date(Date.now() - 86400000 * 1.2).toISOString(),
        createdBy: 'user_admin',
      },
    ],
  },
  {
    id: 'QUO-001023',
    workOrderId: 'WO-001023',
    customerId: 'cust_cafe_carthage',
    customerName: 'Café & Lounge Carthage',
    currentVersion: 1,
    status: 'ACCEPTED',
    validUntil: new Date(Date.now() + 86400000 * 20).toISOString(),
    sentAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    acceptedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    versions: [
      {
        version: 1,
        items: [
          { id: 'qi_w1', productId: 'prod_ap_wifi6_unifi', name: 'Ubiquiti UniFi 6 Pro Access Point (Wi-Fi 6)', type: 'product', quantity: 3, unitPrice: 480, total: 1440 },
          { id: 'qi_w2', productId: 'prod_switch_poe_8port', name: 'Managed Gigabit 8-Port PoE+ Switch (120W)', type: 'product', quantity: 1, unitPrice: 240, total: 240 },
          { id: 'qi_w3', productId: 'prod_cable_cat6_roll', name: 'Cat6 UTP Copper Cable (Drum)', type: 'product', quantity: 1, unitPrice: 260, total: 260 },
          { id: 'qi_w4', productId: 'serv_wifi_deployment_per_ap', name: 'Wi-Fi AP Installation & Roaming Optimization', type: 'service', quantity: 3, unitPrice: 95, total: 285 },
        ],
        subtotal: 2225.00,
        discount: 75.00,
        taxRate: 0.19,
        taxAmount: 408.50,
        total: 2558.50,
        notes: 'Includes separate guest captive portal with customized café branding.',
        createdAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
        createdBy: 'user_admin',
      },
    ],
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'INV-001022',
    workOrderId: 'WO-001022',
    quoteId: 'QUO-001022',
    customerId: 'cust_abc_logistics',
    customerName: 'ABC Logistics Hub',
    amount: 3570.00,
    currency: 'TND',
    issueDate: new Date(Date.now() - 86400000 * 0.8).toISOString(),
    dueAt: new Date(Date.now() + 86400000 * 7).toISOString(),
    status: 'PAID',
    paidAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    paidAmount: 3570.00,
    paymentMethod: 'BANK_TRANSFER',
    paymentReference: 'ATTIJARI-WIRE-992019',
    confirmedBy: 'user_admin',
  },
  {
    id: 'INV-001023',
    workOrderId: 'WO-001023',
    quoteId: 'QUO-001023',
    customerId: 'cust_cafe_carthage',
    customerName: 'Café & Lounge Carthage',
    amount: 2558.50,
    currency: 'TND',
    issueDate: new Date(Date.now() - 3600000 * 12).toISOString(),
    dueAt: new Date(Date.now() + 86400000 * 3).toISOString(),
    status: 'UNPAID',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'APT-001',
    workOrderId: 'WO-001022',
    type: 'INSTALLATION',
    customerName: 'ABC Logistics Hub',
    siteAddress: 'Port de Commerce, Hangar 4B, Sfax 3000',
    technicianId: 'user_tech_slimane',
    technicianName: 'Slimane Trabelsi',
    startAt: new Date(Date.now() + 3600000 * 2).toISOString(), // in 2 hours
    endAt: new Date(Date.now() + 3600000 * 8).toISOString(),
    status: 'CONFIRMED',
    notes: 'Bring 4 4K cameras, 8-ch NVR, and cherry picker boom lift.',
  },
  {
    id: 'APT-002',
    workOrderId: 'WO-001023',
    type: 'SITE_VISIT',
    customerName: 'Café & Lounge Carthage',
    siteAddress: 'Corniche de La Marsa, Tunis 2070',
    technicianId: 'user_tech_zied',
    technicianName: 'Zied Khelil',
    startAt: new Date(Date.now() + 3600000 * 5).toISOString(),
    endAt: new Date(Date.now() + 3600000 * 7).toISOString(),
    status: 'SCHEDULED',
    notes: 'Follow-up on payment check and physical cable pathway confirmation.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditEntry[] = [
  {
    id: 'AUD-001',
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
    actorId: 'user_admin',
    actorName: 'Sonia Guesmi',
    actorRole: 'ADMIN',
    action: 'REQUEST_ACCEPTED',
    targetType: 'WORK_ORDER',
    targetId: 'WO-001022',
    previousState: 'NEW',
    newState: 'WAITING_FOR_CONTACT',
    reason: 'Customer request validated. Instantiated CCTV installation workflow template.',
  },
  {
    id: 'AUD-002',
    timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
    actorId: 'user_admin',
    actorName: 'Sonia Guesmi',
    actorRole: 'ADMIN',
    action: 'PAYMENT_CONFIRMED',
    targetType: 'PAYMENT',
    targetId: 'INV-001022',
    previousState: 'UNPAID',
    newState: 'PAID',
    reason: 'Bank transfer confirmed in bank statement. WORK AUTHORIZED. Installation unlocked.',
  },
];
