/**
 * Authoritative Workflow Templates
 * Used by backend to automatically instantiate tasks upon request acceptance.
 */
import { WorkflowTemplate } from '../types';

export const WORKFLOW_TEMPLATES: Record<string, WorkflowTemplate> = {
  cctv_installation: {
    id: 'cctv_installation',
    name: 'CCTV Security Camera Installation',
    category: 'SURVEILLANCE',
    description: 'End-to-end IP/Analog surveillance installation, cabling, NVR provisioning, remote streaming setup, and customer sign-off.',
    defaultEstimatedDurationHours: 6,
    steps: [
      {
        id: 'contact_customer',
        title: 'Contact Customer & Verify Needs',
        type: 'CONTACT',
        order: 1,
        dependencies: [],
        defaultAssigneeRole: 'ADMIN',
        description: 'Call or WhatsApp customer to clarify site details, requirements, and schedule the preliminary site survey visit.',
      },
      {
        id: 'site_visit',
        title: 'Conduct Site Survey & Technical Inspection',
        type: 'SITE_VISIT',
        order: 2,
        dependencies: ['contact_customer'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Physical inspection of building, cable routing paths, mounting points, power sources, network readiness, and capture photos.',
      },
      {
        id: 'create_quote',
        title: 'Create Quotation & Bill of Quantities',
        type: 'CREATE_QUOTE',
        order: 3,
        dependencies: ['site_visit'],
        defaultAssigneeRole: 'ADMIN',
        description: 'Select required IP cameras, NVR, hard drive, PoE switch, cable drums, connectors, and labour services based on survey results.',
      },
      {
        id: 'customer_approval',
        title: 'Customer Approval of Quote',
        type: 'CUSTOMER_APPROVAL',
        order: 4,
        dependencies: ['create_quote'],
        defaultAssigneeRole: 'ADMIN',
        description: 'Customer reviews quote proposal on web/email and formally accepts terms, requests revisions, or declines.',
        criticalGate: true,
      },
      {
        id: 'create_invoice',
        title: 'Generate Pro-forma / Commercial Invoice',
        type: 'CREATE_INVOICE',
        order: 5,
        dependencies: ['customer_approval'],
        defaultAssigneeRole: 'ACCOUNTANT',
        description: 'System automatically issues commercial invoice upon quote acceptance. Sent to customer with payment instructions.',
      },
      {
        id: 'payment_confirmation',
        title: 'Payment Confirmation & Commercial Gate',
        type: 'PAYMENT',
        order: 6,
        dependencies: ['create_invoice'],
        defaultAssigneeRole: 'ADMIN',
        description: 'CRITICAL WORKFLOW GATE: Verify deposit/full payment before dispatching equipment and technicians. Installation work remains locked until confirmed.',
        criticalGate: true,
      },
      {
        id: 'prepare_equipment',
        title: 'Pick & Prepare Warehouse Equipment',
        type: 'PREPARE_EQUIPMENT',
        order: 7,
        dependencies: ['payment_confirmation'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Kit preparation: cameras, NVR, HDD formatting, patch cords, fasteners, PoE switches, and tool inspection.',
      },
      {
        id: 'mount_and_cabling',
        title: 'Cable Pulling & Physical Camera Mounting',
        type: 'INSTALLATION',
        order: 8,
        dependencies: ['prepare_equipment'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Route shielded Cat6 cables, mount exterior/interior cameras, terminate RJ45 keystones, install NVR in rack or cabinet.',
      },
      {
        id: 'configuration',
        title: 'Configure NVR, Motion Zones & P2P App',
        type: 'CONFIGURATION',
        order: 9,
        dependencies: ['mount_and_cabling'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Set static IP addressing, motion detection zones, recording schedule, user credentials, and cloud P2P mobile remote view.',
      },
      {
        id: 'system_testing',
        title: 'System Commissioning & Angle Verification',
        type: 'TESTING',
        order: 10,
        dependencies: ['configuration'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Day/Night IR verification, frame rate checks, storage retention validation, failover checks, and site clean-up.',
      },
      {
        id: 'customer_confirmation',
        title: 'Customer Training, Handover & Sign-off',
        type: 'CUSTOMER_CONFIRMATION',
        order: 11,
        dependencies: ['system_testing'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Walk customer through live monitor and phone app, capture digital signature, issue warranty sheet, and generate Service Report.',
        criticalGate: true,
      },
    ],
  },

  wifi_installation: {
    id: 'wifi_installation',
    name: 'Enterprise Wi-Fi & Mesh Network',
    category: 'NETWORKING',
    description: 'High-density commercial Wi-Fi deployment, ceiling access points, VLAN segmentation, captive portal, and coverage survey.',
    defaultEstimatedDurationHours: 5,
    steps: [
      {
        id: 'contact_customer',
        title: 'Contact Customer & Verify Needs',
        type: 'CONTACT',
        order: 1,
        dependencies: [],
        defaultAssigneeRole: 'ADMIN',
        description: 'Confirm coverage square meters, expected concurrent devices, bandwidth ISP, and schedule site heat-map survey.',
      },
      {
        id: 'site_visit',
        title: 'RF Site Survey & AP Placement Survey',
        type: 'SITE_VISIT',
        order: 2,
        dependencies: ['contact_customer'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Analyze wall attenuation (concrete, drywall), interference channels, ceiling access, and router location.',
      },
      {
        id: 'create_quote',
        title: 'Prepare Wi-Fi Proposal & Equipment BOM',
        type: 'CREATE_QUOTE',
        order: 3,
        dependencies: ['site_visit'],
        defaultAssigneeRole: 'ADMIN',
        description: 'Select Wi-Fi 6 Access Points, Cloud Gateway / Controller, PoE switch, and installation labor.',
      },
      {
        id: 'customer_approval',
        title: 'Customer Approval of Quote',
        type: 'CUSTOMER_APPROVAL',
        order: 4,
        dependencies: ['create_quote'],
        defaultAssigneeRole: 'ADMIN',
        description: 'Customer accepts proposal and technical design specifications.',
        criticalGate: true,
      },
      {
        id: 'create_invoice',
        title: 'Generate Pro-forma / Commercial Invoice',
        type: 'CREATE_INVOICE',
        order: 5,
        dependencies: ['customer_approval'],
        defaultAssigneeRole: 'ACCOUNTANT',
        description: 'Issue invoice with payment terms and bank details.',
      },
      {
        id: 'payment_confirmation',
        title: 'Payment Confirmation & Commercial Gate',
        type: 'PAYMENT',
        order: 6,
        dependencies: ['create_invoice'],
        defaultAssigneeRole: 'ADMIN',
        description: 'Verify payment before dispatching networking hardware.',
        criticalGate: true,
      },
      {
        id: 'prepare_equipment',
        title: 'Flash Firmware & Adopt APs in Controller',
        type: 'PREPARE_EQUIPMENT',
        order: 7,
        dependencies: ['payment_confirmation'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Pre-configure controller, update AP firmware, label hardware.',
      },
      {
        id: 'mount_and_cabling',
        title: 'Install Cat6 Drops & Mount Access Points',
        type: 'INSTALLATION',
        order: 8,
        dependencies: ['prepare_equipment'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Pull plenum Cat6 to ceiling locations, terminate jacks, and mount AP brackets.',
      },
      {
        id: 'configuration',
        title: 'Configure SSIDs, VLANs & Guest Portal',
        type: 'CONFIGURATION',
        order: 9,
        dependencies: ['mount_and_cabling'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Create Staff and Guest SSIDs with rate limiting, band steering, and fast roaming 802.11k/v/r.',
      },
      {
        id: 'system_testing',
        title: 'Throughput Speed Test & Roaming Audit',
        type: 'TESTING',
        order: 10,
        dependencies: ['configuration'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Conduct speed tests in corner offices, check seamless handover during active voice/video call.',
      },
      {
        id: 'customer_confirmation',
        title: 'Deliver Credentials & Customer Sign-off',
        type: 'CUSTOMER_CONFIRMATION',
        order: 11,
        dependencies: ['system_testing'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Hand over Wi-Fi admin cards and QR codes, obtain customer sign-off signature.',
        criticalGate: true,
      },
    ],
  },

  access_control_installation: {
    id: 'access_control_installation',
    name: 'Biometric Access Control & Intercom',
    category: 'SECURITY',
    description: 'Electromagnetic door locks, RFID keyfobs, biometric facial recognition terminals, and egress push buttons.',
    defaultEstimatedDurationHours: 6,
    steps: [
      {
        id: 'contact_customer',
        title: 'Contact Customer & Door Audit',
        type: 'CONTACT',
        order: 1,
        dependencies: [],
        defaultAssigneeRole: 'ADMIN',
        description: 'Identify door types (glass, wood, fire-rated steel), user count, and security level.',
      },
      {
        id: 'site_visit',
        title: 'Door Hardware & Power Survey',
        type: 'SITE_VISIT',
        order: 2,
        dependencies: ['contact_customer'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Inspect door frames, power supply locations, fail-safe vs fail-secure emergency compliance.',
      },
      {
        id: 'create_quote',
        title: 'Create Access Control Quotation',
        type: 'CREATE_QUOTE',
        order: 3,
        dependencies: ['site_visit'],
        defaultAssigneeRole: 'ADMIN',
        description: 'Calculate maglocks, brackets (ZL/U), readers, controller boards, UPS backup batteries.',
      },
      {
        id: 'customer_approval',
        title: 'Customer Approval of Quote',
        type: 'CUSTOMER_APPROVAL',
        order: 4,
        dependencies: ['create_quote'],
        defaultAssigneeRole: 'ADMIN',
        description: 'Customer accepts hardware list and door entry policy.',
        criticalGate: true,
      },
      {
        id: 'create_invoice',
        title: 'Generate Commercial Invoice',
        type: 'CREATE_INVOICE',
        order: 5,
        dependencies: ['customer_approval'],
        defaultAssigneeRole: 'ACCOUNTANT',
        description: 'Issue invoice with payment terms.',
      },
      {
        id: 'payment_confirmation',
        title: 'Payment Gate Confirmation',
        type: 'PAYMENT',
        order: 6,
        dependencies: ['create_invoice'],
        defaultAssigneeRole: 'ADMIN',
        description: 'Work cannot begin until payment is confirmed by admin.',
        criticalGate: true,
      },
      {
        id: 'prepare_equipment',
        title: 'Assemble Controller & Battery Enclosure',
        type: 'PREPARE_EQUIPMENT',
        order: 7,
        dependencies: ['payment_confirmation'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Wire 12V 5A power supply, test battery backup switchover.',
      },
      {
        id: 'mount_and_cabling',
        title: 'Install Locks, Exit Buttons & Readers',
        type: 'INSTALLATION',
        order: 8,
        dependencies: ['prepare_equipment'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Mount magnetic lock, install green emergency break-glass unit and optical exit sensor.',
      },
      {
        id: 'configuration',
        title: 'Enroll Users & Access Time Zones',
        type: 'CONFIGURATION',
        order: 9,
        dependencies: ['mount_and_cabling'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Configure door unlock duration, holiday schedules, and register master administrator.',
      },
      {
        id: 'system_testing',
        title: 'Safety Release & Fail-Safe Testing',
        type: 'TESTING',
        order: 10,
        dependencies: ['configuration'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Test power cut-off release, tamper alarms, and emergency egress compliance.',
      },
      {
        id: 'customer_confirmation',
        title: 'Staff Training & Customer Sign-off',
        type: 'CUSTOMER_CONFIRMATION',
        order: 11,
        dependencies: ['system_testing'],
        defaultAssigneeRole: 'TECHNICIAN',
        description: 'Train client on card provisioning, obtain final signature.',
        criticalGate: true,
      },
    ],
  },

  network_installation: {
    id: 'network_installation',
    name: 'Structured Cabling & Server Rack Setup',
    category: 'NETWORKING',
    description: 'Cat6/Cat6A structured cabling, patch panels, 19-inch rack cabinet assembly, cable management, and Fluke certification.',
    defaultEstimatedDurationHours: 8,
    steps: [
      { id: 'contact_customer', title: 'Contact Customer & Scoping', type: 'CONTACT', order: 1, dependencies: [], defaultAssigneeRole: 'ADMIN', description: 'Count data drops and telecom demarcation point.' },
      { id: 'site_visit', title: 'Route Survey & Cable Pathways', type: 'SITE_VISIT', order: 2, dependencies: ['contact_customer'], defaultAssigneeRole: 'TECHNICIAN', description: 'Check raceways, ceiling trays, core drilling needs.' },
      { id: 'create_quote', title: 'Cabling & Rack Quotation', type: 'CREATE_QUOTE', order: 3, dependencies: ['site_visit'], defaultAssigneeRole: 'ADMIN', description: 'Bill of materials for cable rolls, faceplates, rack accessories.' },
      { id: 'customer_approval', title: 'Customer Quote Acceptance', type: 'CUSTOMER_APPROVAL', order: 4, dependencies: ['create_quote'], defaultAssigneeRole: 'ADMIN', description: 'Customer approval.', criticalGate: true },
      { id: 'create_invoice', title: 'Invoice Issuance', type: 'CREATE_INVOICE', order: 5, dependencies: ['customer_approval'], defaultAssigneeRole: 'ACCOUNTANT', description: 'Issue commercial invoice.' },
      { id: 'payment_confirmation', title: 'Payment Gate Verification', type: 'PAYMENT', order: 6, dependencies: ['create_invoice'], defaultAssigneeRole: 'ADMIN', description: 'Admin verifies payment.', criticalGate: true },
      { id: 'prepare_equipment', title: 'Prepare Patch Panels & Keystones', type: 'PREPARE_EQUIPMENT', order: 7, dependencies: ['payment_confirmation'], defaultAssigneeRole: 'TECHNICIAN', description: 'Organize drums, punch-down tools, tester.' },
      { id: 'mount_and_cabling', title: 'Cable Pulling & Rack Termination', type: 'INSTALLATION', order: 8, dependencies: ['prepare_equipment'], defaultAssigneeRole: 'TECHNICIAN', description: 'Pull lines through conduit, punch down to patch panel T568B.' },
      { id: 'configuration', title: 'Patching & Switch Link Aggregation', type: 'CONFIGURATION', order: 9, dependencies: ['mount_and_cabling'], defaultAssigneeRole: 'TECHNICIAN', description: 'Patch cables with color coding and labeling.' },
      { id: 'system_testing', title: 'Wiremap & Continuity Testing', type: 'TESTING', order: 10, dependencies: ['configuration'], defaultAssigneeRole: 'TECHNICIAN', description: 'Certify every drop with network cable tester.' },
      { id: 'customer_confirmation', title: 'Rack Handover & Sign-off', type: 'CUSTOMER_CONFIRMATION', order: 11, dependencies: ['system_testing'], defaultAssigneeRole: 'TECHNICIAN', description: 'Deliver cable map documentation and obtain signature.', criticalGate: true },
    ],
  },

  alarm_installation: {
    id: 'alarm_installation',
    name: 'Intruder Alarm & Perimeter Defense',
    category: 'SECURITY',
    description: 'PIR motion detectors, magnetic door contacts, dual-tech glass break sensors, external solar sirens, and GSM communicator.',
    defaultEstimatedDurationHours: 5,
    steps: [
      { id: 'contact_customer', title: 'Contact Customer & Vulnerability Review', type: 'CONTACT', order: 1, dependencies: [], defaultAssigneeRole: 'ADMIN', description: 'Review security concerns and perimeter points.' },
      { id: 'site_visit', title: 'Sensor Placement Survey', type: 'SITE_VISIT', order: 2, dependencies: ['contact_customer'], defaultAssigneeRole: 'TECHNICIAN', description: 'Check pet immunity needs, blind spots, siren mounting height.' },
      { id: 'create_quote', title: 'Alarm Proposal & BOM', type: 'CREATE_QUOTE', order: 3, dependencies: ['site_visit'], defaultAssigneeRole: 'ADMIN', description: 'Price hybrid panel, PIRs, siren, battery, keypad.' },
      { id: 'customer_approval', title: 'Customer Approval', type: 'CUSTOMER_APPROVAL', order: 4, dependencies: ['create_quote'], defaultAssigneeRole: 'ADMIN', description: 'Customer accepts proposal.', criticalGate: true },
      { id: 'create_invoice', title: 'Invoice Issuance', type: 'CREATE_INVOICE', order: 5, dependencies: ['customer_approval'], defaultAssigneeRole: 'ACCOUNTANT', description: 'Issue commercial invoice.' },
      { id: 'payment_confirmation', title: 'Payment Gate Verification', type: 'PAYMENT', order: 6, dependencies: ['create_invoice'], defaultAssigneeRole: 'ADMIN', description: 'Verify payment before installation.', criticalGate: true },
      { id: 'prepare_equipment', title: 'Enroll Sensors to Panel', type: 'PREPARE_EQUIPMENT', order: 7, dependencies: ['payment_confirmation'], defaultAssigneeRole: 'TECHNICIAN', description: 'Pair wireless/wired detectors and insert GSM SIM card.' },
      { id: 'mount_and_cabling', title: 'Mount Sensors, Keypad & Siren', type: 'INSTALLATION', order: 8, dependencies: ['prepare_equipment'], defaultAssigneeRole: 'TECHNICIAN', description: 'Secure brackets, mount exterior strobe siren.' },
      { id: 'configuration', title: 'Zone Partitioning & Phone Alerts', type: 'CONFIGURATION', order: 9, dependencies: ['mount_and_cabling'], defaultAssigneeRole: 'TECHNICIAN', description: 'Program entry/exit delay (30s), night arm zones, SMS alert numbers.' },
      { id: 'system_testing', title: 'Walk Test & Alarm Trigger Simulation', type: 'TESTING', order: 10, dependencies: ['configuration'], defaultAssigneeRole: 'TECHNICIAN', description: 'Trigger each zone, verify siren decibels and SMS dispatch.' },
      { id: 'customer_confirmation', title: 'User PIN Code Handover & Sign-off', type: 'CUSTOMER_CONFIRMATION', order: 11, dependencies: ['system_testing'], defaultAssigneeRole: 'TECHNICIAN', description: 'Set customer master PIN code and complete service report.', criticalGate: true },
    ],
  },

  satellite_installation: {
    id: 'satellite_installation',
    name: 'Satellite Dish & Central Distribution',
    category: 'BROADCAST',
    description: 'Multi-satellite reception (Nilesat, Astra, Hotbird), optical or coaxial multi-switch installation for apartments and villas.',
    defaultEstimatedDurationHours: 4,
    steps: [
      { id: 'contact_customer', title: 'Contact Customer & Channel Needs', type: 'CONTACT', order: 1, dependencies: [], defaultAssigneeRole: 'ADMIN', description: 'Check required orbital satellites and outlet points.' },
      { id: 'site_visit', title: 'Rooftop Azimuth & Elevation Survey', type: 'SITE_VISIT', order: 2, dependencies: ['contact_customer'], defaultAssigneeRole: 'TECHNICIAN', description: 'Verify clear line of sight, mount durability, wind resistance.' },
      { id: 'create_quote', title: 'Satellite & Switch Quote', type: 'CREATE_QUOTE', order: 3, dependencies: ['site_visit'], defaultAssigneeRole: 'ADMIN', description: 'Dish size, quattro LNBs, multiswitch 17x8, RG6 cable.' },
      { id: 'customer_approval', title: 'Customer Approval', type: 'CUSTOMER_APPROVAL', order: 4, dependencies: ['create_quote'], defaultAssigneeRole: 'ADMIN', description: 'Customer approval.', criticalGate: true },
      { id: 'create_invoice', title: 'Invoice Issuance', type: 'CREATE_INVOICE', order: 5, dependencies: ['customer_approval'], defaultAssigneeRole: 'ACCOUNTANT', description: 'Issue invoice.' },
      { id: 'payment_confirmation', title: 'Payment Gate Verification', type: 'PAYMENT', order: 6, dependencies: ['create_invoice'], defaultAssigneeRole: 'ADMIN', description: 'Verify payment before installation.', criticalGate: true },
      { id: 'prepare_equipment', title: 'Inspect LNBs & Align Tool', type: 'PREPARE_EQUIPMENT', order: 7, dependencies: ['payment_confirmation'], defaultAssigneeRole: 'TECHNICIAN', description: 'Calibrate digital satellite meter.' },
      { id: 'mount_and_cabling', title: 'Mount Dish & Pull RG6 Cabling', type: 'INSTALLATION', order: 8, dependencies: ['prepare_equipment'], defaultAssigneeRole: 'TECHNICIAN', description: 'Anchor mast, route cables, install multiswitch.' },
      { id: 'configuration', title: 'Fine-tune Transponder Alignment', type: 'CONFIGURATION', order: 9, dependencies: ['mount_and_cabling'], defaultAssigneeRole: 'TECHNICIAN', description: 'Maximize MER (Modulation Error Ratio) and C/N signal quality.' },
      { id: 'system_testing', title: 'Signal Quality Scan on All Outlets', type: 'TESTING', order: 10, dependencies: ['configuration'], defaultAssigneeRole: 'TECHNICIAN', description: 'Scan channels on TV receivers in all designated rooms.' },
      { id: 'customer_confirmation', title: 'Customer Handover & Sign-off', type: 'CUSTOMER_CONFIRMATION', order: 11, dependencies: ['system_testing'], defaultAssigneeRole: 'TECHNICIAN', description: 'Customer sign-off and report.', criticalGate: true },
    ],
  },

  iptv_installation: {
    id: 'iptv_installation',
    name: 'Commercial IPTV & Hospitality Streaming',
    category: 'BROADCAST',
    description: 'Centralized IPTV headend, hotel TV distribution, interactive guest portal, multicast network streams.',
    defaultEstimatedDurationHours: 6,
    steps: [
      { id: 'contact_customer', title: 'Contact Customer & Channel Package', type: 'CONTACT', order: 1, dependencies: [], defaultAssigneeRole: 'ADMIN', description: 'Confirm stream count and network layout.' },
      { id: 'site_visit', title: 'Network Multicast Readiness Survey', type: 'SITE_VISIT', order: 2, dependencies: ['contact_customer'], defaultAssigneeRole: 'TECHNICIAN', description: 'Check IGMP snooping support on existing switches.' },
      { id: 'create_quote', title: 'IPTV Server & Set-top Box Quote', type: 'CREATE_QUOTE', order: 3, dependencies: ['site_visit'], defaultAssigneeRole: 'ADMIN', description: 'IPTV Gateway server, transcoders, client boxes.' },
      { id: 'customer_approval', title: 'Customer Approval', type: 'CUSTOMER_APPROVAL', order: 4, dependencies: ['create_quote'], defaultAssigneeRole: 'ADMIN', description: 'Customer approval.', criticalGate: true },
      { id: 'create_invoice', title: 'Invoice Issuance', type: 'CREATE_INVOICE', order: 5, dependencies: ['customer_approval'], defaultAssigneeRole: 'ACCOUNTANT', description: 'Issue commercial invoice.' },
      { id: 'payment_confirmation', title: 'Payment Gate Verification', type: 'PAYMENT', order: 6, dependencies: ['create_invoice'], defaultAssigneeRole: 'ADMIN', description: 'Verify payment before deployment.', criticalGate: true },
      { id: 'prepare_equipment', title: 'Provision Stream Gateway Server', type: 'PREPARE_EQUIPMENT', order: 7, dependencies: ['payment_confirmation'], defaultAssigneeRole: 'TECHNICIAN', description: 'Install Linux IPTV middleware, configure channel bouquets.' },
      { id: 'mount_and_cabling', title: 'Rack Installation & STB Deployment', type: 'INSTALLATION', order: 8, dependencies: ['prepare_equipment'], defaultAssigneeRole: 'TECHNICIAN', description: 'Rack mount headend, connect to core switch, deploy STBs.' },
      { id: 'configuration', title: 'Configure IGMP Multicast & EPG', type: 'CONFIGURATION', order: 9, dependencies: ['mount_and_cabling'], defaultAssigneeRole: 'TECHNICIAN', description: 'Tune multicast addresses and electronic program guide.' },
      { id: 'system_testing', title: 'Channel Switching Latency & Buffer Test', type: 'TESTING', order: 10, dependencies: ['configuration'], defaultAssigneeRole: 'TECHNICIAN', description: 'Validate jitter < 2ms, zero packet drop across all screens.' },
      { id: 'customer_confirmation', title: 'Customer Handover & Sign-off', type: 'CUSTOMER_CONFIRMATION', order: 11, dependencies: ['system_testing'], defaultAssigneeRole: 'TECHNICIAN', description: 'Customer sign-off and report.', criticalGate: true },
    ],
  },

  maintenance: {
    id: 'maintenance',
    name: 'Scheduled Preventive Maintenance',
    category: 'SERVICES',
    description: 'Quarterly/annual lens cleaning, firmware security patches, backup battery load testing, and retention validation.',
    defaultEstimatedDurationHours: 3,
    steps: [
      { id: 'contact_customer', title: 'Contact Customer & Access Clearance', type: 'CONTACT', order: 1, dependencies: [], defaultAssigneeRole: 'ADMIN', description: 'Arrange security badge clearance and inspection window.' },
      { id: 'site_visit', title: 'On-site Initial Health Diagnostic', type: 'SITE_VISIT', order: 2, dependencies: ['contact_customer'], defaultAssigneeRole: 'TECHNICIAN', description: 'Review system logs for SMART disk errors or offline devices.' },
      { id: 'create_quote', title: 'Consumables & Parts Proposal (if needed)', type: 'CREATE_QUOTE', order: 3, dependencies: ['site_visit'], defaultAssigneeRole: 'ADMIN', description: 'Replacement batteries or degraded cabling items.' },
      { id: 'customer_approval', title: 'Approval of Maintenance Scope', type: 'CUSTOMER_APPROVAL', order: 4, dependencies: ['create_quote'], defaultAssigneeRole: 'ADMIN', description: 'Customer sign-off on replacement items.', criticalGate: true },
      { id: 'create_invoice', title: 'Maintenance Invoice Issuance', type: 'CREATE_INVOICE', order: 5, dependencies: ['customer_approval'], defaultAssigneeRole: 'ACCOUNTANT', description: 'Issue maintenance contract invoice.' },
      { id: 'payment_confirmation', title: 'Payment Gate Verification', type: 'PAYMENT', order: 6, dependencies: ['create_invoice'], defaultAssigneeRole: 'ADMIN', description: 'Payment check.', criticalGate: true },
      { id: 'prepare_equipment', title: 'Prepare Cleaning & Test Equipment', type: 'PREPARE_EQUIPMENT', order: 7, dependencies: ['payment_confirmation'], defaultAssigneeRole: 'TECHNICIAN', description: 'Microfiber optics kits, UPS battery analyzer, firmware drive.' },
      { id: 'mount_and_cabling', title: 'Execute Physical Cleaning & Cable Check', type: 'INSTALLATION', order: 8, dependencies: ['prepare_equipment'], defaultAssigneeRole: 'TECHNICIAN', description: 'Clean domes, re-torque mounting screws, inspect weather seals.' },
      { id: 'configuration', title: 'Apply Security Patches & Config Backup', type: 'CONFIGURATION', order: 9, dependencies: ['mount_and_cabling'], defaultAssigneeRole: 'TECHNICIAN', description: 'Upgrade NVR/controller firmware and export encrypted backup config.' },
      { id: 'system_testing', title: 'Battery Load Test & Storage Audit', type: 'TESTING', order: 10, dependencies: ['configuration'], defaultAssigneeRole: 'TECHNICIAN', description: 'Disconnect AC mains to test UPS endurance, check 30-day retention.' },
      { id: 'customer_confirmation', title: 'Maintenance Certificate & Sign-off', type: 'CUSTOMER_CONFIRMATION', order: 11, dependencies: ['system_testing'], defaultAssigneeRole: 'TECHNICIAN', description: 'Issue signed preventive maintenance report with recommendations.', criticalGate: true },
    ],
  },

  troubleshooting: {
    id: 'troubleshooting',
    name: 'Urgent System Troubleshooting & Repair',
    category: 'SERVICES',
    description: 'Rapid diagnostic and component replacement for offline cameras, intermittent network drops, or failed power supplies.',
    defaultEstimatedDurationHours: 3,
    steps: [
      { id: 'contact_customer', title: 'Urgent Triage & Symptom Assessment', type: 'CONTACT', order: 1, dependencies: [], defaultAssigneeRole: 'ADMIN', description: 'Gather exact failure symptoms, error beeps, and schedule emergency visit.' },
      { id: 'site_visit', title: 'Hardware Diagnostic & Fault Isolation', type: 'SITE_VISIT', order: 2, dependencies: ['contact_customer'], defaultAssigneeRole: 'TECHNICIAN', description: 'Trace cable continuity, test PoE budget, verify power supply voltages.' },
      { id: 'create_quote', title: 'Emergency Repair Quotation', type: 'CREATE_QUOTE', order: 3, dependencies: ['site_visit'], defaultAssigneeRole: 'ADMIN', description: 'Replacement parts (switch, power supply, camera) and repair labor.' },
      { id: 'customer_approval', title: 'Customer Approval of Repair Scope', type: 'CUSTOMER_APPROVAL', order: 4, dependencies: ['create_quote'], defaultAssigneeRole: 'ADMIN', description: 'Fast customer sign-off.', criticalGate: true },
      { id: 'create_invoice', title: 'Invoice Issuance', type: 'CREATE_INVOICE', order: 5, dependencies: ['customer_approval'], defaultAssigneeRole: 'ACCOUNTANT', description: 'Emergency repair invoice.' },
      { id: 'payment_confirmation', title: 'Payment Gate Verification', type: 'PAYMENT', order: 6, dependencies: ['create_invoice'], defaultAssigneeRole: 'ADMIN', description: 'Admin payment authorization.', criticalGate: true },
      { id: 'prepare_equipment', title: 'Prepare Replacement Hardware', type: 'PREPARE_EQUIPMENT', order: 7, dependencies: ['payment_confirmation'], defaultAssigneeRole: 'TECHNICIAN', description: 'Retrieve matching replacement units from service van.' },
      { id: 'mount_and_cabling', title: 'Replace Defective Components', type: 'INSTALLATION', order: 8, dependencies: ['prepare_equipment'], defaultAssigneeRole: 'TECHNICIAN', description: 'Swap failed power supply, re-terminate corroded RJ45 connector.' },
      { id: 'configuration', title: 'Restore Settings & Synchronize Device', type: 'CONFIGURATION', order: 9, dependencies: ['mount_and_cabling'], defaultAssigneeRole: 'TECHNICIAN', description: 'Restore camera parameters, verify streaming bitrate.' },
      { id: 'system_testing', title: 'Stability Stress Test & Soak Run', type: 'TESTING', order: 10, dependencies: ['configuration'], defaultAssigneeRole: 'TECHNICIAN', description: 'Verify 0 dropped packets over 15-minute diagnostic logging.' },
      { id: 'customer_confirmation', title: 'Incident Resolution & Customer Sign-off', type: 'CUSTOMER_CONFIRMATION', order: 11, dependencies: ['system_testing'], defaultAssigneeRole: 'TECHNICIAN', description: 'Capture customer signature and deliver resolution report.', criticalGate: true },
    ],
  },
};
